export const FETCH_CHEATS_SUCCESS = 'FETCH_CHEATS_SUCCESS';
export const FETCH_CHEATS_FAILURE = 'FETCH_CHEATS_FAILURE';
export const SEARCH_CHEATS = 'SEARCH_CHEATS';
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const LOGOUT = 'LOGOUT';
